import numpy as np      
import cv2
qr_string = """
WWWWWWWWWWWWWWWWWWWWWWW
WBBBBBBBWBBWWWWBBBBBBBW
WBWWWWWBWBBBBWWBWWWWWBW
WBWBBBWBWBWWBBWBWBBBWBW
WBWBBBWBWBWWBBWBWBBBWBW
WBWBBBWBWBWBBBWBWBBBWBW
WBWWWWWBWWBWBBWBWWWWWBW
WBBBBBBBWBWBWBWBBBBBBBW
WWWWWWWWWBBBBWWWWWWWWWW
WWBWBWBBWBBBWWBBWBBBBBW
WBWBWWBWWBBWWWBWWWBWBBW
WWWWWBBBBWBWWBBWBWWBWWW
WWBWBBWWBWWBWBBWBWWBWBW
WBWWWBBBBBBWWWBBBBBWWWW
WWWWWWWWWBWBWBBWBWWBWBW
WBBBBBBBWWWWWWBBBWWWWWW
WBWWWWWBWBBWBWWBWBBWBWW
WBWBBBWBWWWBBBWWWWWBBBW
WBWBBBWBWBBBWWBWWBBBWWW
WBWBBBWBWWBBBWWWBWBBBBW
WBWWWWWBWBBWBBBWWBWWWBW
WBBBBBBBWWBWWWBWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWW
"""

def get_real():
    array = qr_string.strip().split("\n")
    qr = []
    for row in array:
        x = []
        for letter in row:
            x.append(1 if letter == 'W' else 0)
        qr.append(x)
    qr = np.array(qr) * 255
    qr = np.array(qr, dtype=np.uint8)
    return qr
if __name__ == '__main__':
    qr = get_real()
    cv2.imwrite('./qr_real.png', qr)
